# Generated by Django 4.1 on 2023-08-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="movie_img",
            field=models.ImageField(default="knjhh", upload_to="gallery"),
            preserve_default=False,
        ),
    ]
